# -*- coding: utf-8 -*-
"""CryptoBuddy_AI_Chatbot_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jhoeAOzRYw4FiD-Qpy_ftE8UV4DMt6G
"""

# Predefined cryptocurrency database

crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8
    }
}

# crypto_chatbot.py
# A friendly crypto investment advisor bot using rule-based AI logic

# Greeting Message

print("👋 Hello! I’m CryptoBuddy – your friendly crypto guide!")
print("Ask me anything about crypto trends, profitability, or sustainability!")
print("Type 'exit' or 'quit' to end the chat.\n")

# Recommend crypto based on query

def recommend_crypto(user_query):
    if "sustainable" in user_query:
        best = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
        print(f"CryptoBuddy:  Go with {best}! It’s eco-friendly and has great potential.")

    elif "trending" in user_query or "rising" in user_query:
        trending = [k for k, v in crypto_db.items() if v["price_trend"] == "rising"]
        print(f"CryptoBuddy:  These are currently trending up: {', '.join(trending)}")

    elif "long-term" in user_query or "growth" in user_query:
        for name, data in crypto_db.items():
            if data["price_trend"] == "rising" and data["sustainability_score"] > 7:
                print(f"CryptoBuddy: 📈 {name} is your best bet for long-term growth!")
                return
        print("CryptoBuddy: 🤔 Hmm, no perfect match found. Try diversifying your investments.")

    elif "profitable" in user_query or "high return" in user_query:
        for name, data in crypto_db.items():
            if data["price_trend"] == "rising" and data["market_cap"] == "high":
                print(f"CryptoBuddy: 💸 {name} looks profitable right now!")
                return
        print("CryptoBuddy: 🤷 Nothing looks super profitable at the moment.")

    elif "bitcoin" in user_query:
        print("CryptoBuddy: Bitcoin is the OG but consumes a lot of energy ⚡")

    elif "disclaimer" in user_query:
        print("CryptoBuddy: 🚨 Crypto is risky. Always do your own research before investing!")

    else:
        print("CryptoBuddy: 🧐 I didn’t get that. Try asking about trends, sustainability, or profitability.")

# Get user input

def get_user_query():
    return input("You: ").lower()

# Run chatbot loop

while True:
    query = get_user_query()
    if query in ["exit", "quit"]:
        print("CryptoBuddy: 👋 Catch you later! Happy investing!")
        break
    recommend_crypto(query)

# Function to get user input
def get_user_query():
    return input("You: ").lower()